const arrays = [
  {
    type: 'years',
    array: [
      'all',
      'upcoming',
      '2020s',
      '2010s',
      '1990s',
      '1980s',
      '1970s',
      '1960s',
      '1950s',
      '1940s',
      '1930s',
      '1920s',
      '1910s',
      '1900s',
    ],
  },
  {
    type: 'ratings',
    array: ['Highest First', 'Lowest First'],
  },
  {
    type: 'popularity',
    array: ['this year', 'this month', 'this week'],
  },
  {
    type: 'genres',
    array: [
      'Action',
      'Adventure',
      'Animation',
      'Comedy',
      'Crime',
      'Documentary',
      'Drama',
      'Family',
      'Fantasy',
      'History',
      'Horror',
      'Music',
      'Mystery',
      'Romance',
      'Science Fiction',
      'TV Movie',
      'Thriller',
      'War',
      'Western',
    ],
  },
];
export default arrays;
