const filterOptions = [
  {
    title: "years",
    values: [
      "all",
      "upcoming",
      "2020s",
      "2010s",
      "1990s",
      "1980s",
      "1970s",
      "1960s",
      "1950s",
      "1940s",
      "1930s",
      "1920s",
      "1910s",
      "1900s",
    ],
  },
  {
    title: "ratings",
    values: ["Highest First", "Lowest First"],
  },
  {
    title: "popularity",
    values: ["this year", "this month", "this week"],
  },
  {
    title: "genres",
    values: [
      "Action",
      "Adventure",
      "Animation",
      "Comedy",
      "Crime",
      "Documentary",
      "Drama",
      "Family",
      "Fantasy",
      "History",
      "Horror",
      "Music",
      "Mystery",
      "Romance",
      "Science Fiction",
      "TV Movie",
      "Thriller",
      "War",
      "Western",
    ],
  },
];

export default filterOptions;
